language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- "1.10"
git:
  depth: 500
install:
- go get github.com/kardianos/govendor
- ./tools/build.sh
- ./tools/package.sh
- ./tools/publish.sh
script:
- make test
- make testacc
- make vendor-status
- make vet
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: WaHQFV7YJ4OAiOkXZpzGfIbTS197NWdAs25lz5JiWDevKn8BSBpo1TP97HoRH9hbJPnpIW244AMhLDoDQSpY6+iH2x57zvNuVDuBZwm3V5CCsnN3ggTJGvtzkUQaMxpz5S9YXDPovtGScXVPAXe0JhQUTPzTceA0oA+M9kqaP+sTZUY7PsKNUev6N2pdmY/V58XzEOC+TYjOO138X7+GMz8J1YRJdw9bvRGJKKKQSVhObItqnzjis2NovuhfwKMr1QKfF6R5/uiJwE9Dtw2vevgwuwSS9pX+e8M21BPSAx57G7LOy5gAm6aQJNYGz5Dou9NefLVK8vJvPR2CkVDtF1Su5qn4rSlFG1+CjtXeDf85RjrUpbm8nrThvVDzi0h8ySB+g6omf4TXPjXpqqSnGMT8lVVX2K00GIbEwhBMsNtiqtlUOadN1/BPKqxtKkNWD35RXJbJw/+Y8oIYbe1Asatx1FYfbyiGoXZgvFU+EBXwG0B+Ovu+VjDOKTC5xYRNIMM2QGLSn8PhHr1wlZrOGlwZ2czcJsYGFLuG4W8V1v31tNiRdbvmISVP+8wUlHY3RYJK7p0IFG6GNWQzNkrM/miEpoL1VRsXTFJjLhHE+OQhY+z5unfLcJuaEWQy39qam6NR1l7ozyMi2hVt9xr0Yv2d6SPE1/Pd5sqbJzHfMOM=
  file:
  - terraform-provider-drp.zip
  - terraform-provider-drp.sha256
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
- provider: s3
  access_key_id: AKIAJY25W4N3CA7NRHJQ
  secret_access_key:
    secure: nDHSts0PQt0Mqv7MERkcKdnB5pPJ6bqN8oXla8JNAhYqxwMSarPcYObTDDYeKodH62WRWCY3s/ZocH1jNm1fN659mJRKIgndKseVQccQ+519JBC7qpNxvta3IM49FhKJOoI40hJIPnFzzcpOxAmkNO83JNjX0ubFqIM42IJoeHhwcN8KZDSWG/Dnl817acTmQXkqg8Iexr9TO9ZEb41Ho1AzowEo+mh2yIGywkGlk9A9cLRf2UFGM5qWtJSflctT69T+KUI9PgAuwOYpZ1KvUwFdPOgmz93Hw1pf5Gx4CNVqQOcT/mZm4z+usDo54SUWNfoS+8nGxZ/5AEQNKPuBgh8qmJ9a6JqWS2IW71tynHzq7W5/kMh206aBSbVt6N0ZcNBK3wNqcvYfSYYgBF+kKZOJ6hdpJS461Wxw2TEvBCx0l1TyNUsRehznkYdl3feR2qumcdyjLderrR/EIYTnVVY8PvsOxYK/uvzR4gkK7+ON8LlRdEjI0rbZncBYJZlJSlEuMw2zXsIlV4czn51T2FMJAwNAVxgXPSShe4PHEkPvb1vy5KWCt0aEokUpiUIkct8O9LqWxpD+sUQ7vgCgCTWAa46VoSi8z+UNCobxqiX7a5Y67ef+JWzxCi4Bo9ciAEdcFRmmUA2E4iTLtguXU7CWat/cUkUcRZPIAfC+2FU=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
