language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- "1.10"
git:
  depth: 500
install:
- go get github.com/kardianos/govendor
- ./tools/build.sh
- ./tools/package.sh
- ./tools/publish.sh
script:
- make test
- make testacc
- make vendor-status
- make vet
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: rxa+NTKZWDfRs95+nvsBVaeba0ppF2Hdi5dGlzZZ9jI5i764B1yCzgj2LFSOj3vHoF1pPejhWh6KLpDaxhbKP3kH4Kyzu7esX/sCnj4bqoyVY8xzyHYN7anCiTLX5cKjS7zePKqKYmyujRJ8lTLcBetQLqqhjOcVtK06HwMOfIbnIfK/Up6OToijTMICehf1lgU0O6lhtKGcvcESo9+y/jftU+RMZyzb0MEckdXM4GKYW4eBy3owNG59FSnRPeFUHqn4/vaiZFFt6TNzvk6ljC9UtybCv03KxHhvAK+MDb1E+NqrCjAlih+peMJZbd3iZa0gl5sEQJJOpX7I1NGZ/tdAkpuZ/S8AoPcP/4JmCRYJl7X2SfraGc5h9RK4ZYFsOPfJBQIrnIB16Z9cyU2wT4bHSPU73WtitVG4T+QhgsgL7nTN9/uzowcJqKXZeqMBsRjgRCLnS+Tamjl5Zp6C0uuYs54pae89Phdmj9klMJdC4tiw1sKW2NZ+KQxkQ3KgMIXqIJzDpE9Rg0yHGN1O4SXJFFDKn6HSEHg0WWQ/6kGl873PiOoLu52zqKLIbYi+hdGYuWn7OQeP1ooaXc+TJP0QCXeMHGdn1V0cJT72OCHdD5aJar2PAHo03bdomQvXIyE4rIOZmjrBCJ7ztt4zHhWK1Mbhj5ekPBP24SOXXpk=
  file:
  - terraform-provider-drp.zip
  - terraform-provider-drp.sha256
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
- provider: s3
  access_key_id: AKIAJY25W4N3CA7NRHJQ
  secret_access_key:
    secure: nDHSts0PQt0Mqv7MERkcKdnB5pPJ6bqN8oXla8JNAhYqxwMSarPcYObTDDYeKodH62WRWCY3s/ZocH1jNm1fN659mJRKIgndKseVQccQ+519JBC7qpNxvta3IM49FhKJOoI40hJIPnFzzcpOxAmkNO83JNjX0ubFqIM42IJoeHhwcN8KZDSWG/Dnl817acTmQXkqg8Iexr9TO9ZEb41Ho1AzowEo+mh2yIGywkGlk9A9cLRf2UFGM5qWtJSflctT69T+KUI9PgAuwOYpZ1KvUwFdPOgmz93Hw1pf5Gx4CNVqQOcT/mZm4z+usDo54SUWNfoS+8nGxZ/5AEQNKPuBgh8qmJ9a6JqWS2IW71tynHzq7W5/kMh206aBSbVt6N0ZcNBK3wNqcvYfSYYgBF+kKZOJ6hdpJS461Wxw2TEvBCx0l1TyNUsRehznkYdl3feR2qumcdyjLderrR/EIYTnVVY8PvsOxYK/uvzR4gkK7+ON8LlRdEjI0rbZncBYJZlJSlEuMw2zXsIlV4czn51T2FMJAwNAVxgXPSShe4PHEkPvb1vy5KWCt0aEokUpiUIkct8O9LqWxpD+sUQ7vgCgCTWAa46VoSi8z+UNCobxqiX7a5Y67ef+JWzxCi4Bo9ciAEdcFRmmUA2E4iTLtguXU7CWat/cUkUcRZPIAfC+2FU=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
